name: ğŸ¤– Auto Merge Dependabot PRs

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ğŸ Init,ğŸ§ª Test]
    types: [completed]
    branches: ['!main']

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
      - name: Config
        run: |
          git config --global user.email "kj1ktk@gmail.com"
          git config --global user.name "Takuma Kajikawa"
      - name: Auto-approve Dependabot PRs
        run: gh pr review ${{ github.event.check_suite.pull_requests[0].number }} --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge Dependabot PRs
        run: gh pr merge ${{ github.event.check_suite.pull_requests[0].number }} --merge --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
